import "./globals.css"
import Header from "@/components/Header"
import { Suisse } from "@/public/Suisse/Suisse"
import { Aeonik } from "@/public/Aeonik cyr/Aeonik"
import { EuclidCircularA } from "@/public/Euclid Circular cyr/Euclid-Circular"
import { MaisonNeue } from "@/public/Maison Neue 3.002 cyr/MaisonNeue"



import { C } from "@/types/child"
import NextTopLoader from "nextjs-toploader"
import { Toaster } from "@/components/ui/toaster"



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: C) {
  return (
    <html lang="en">
      <body className={`${Suisse.className} bg-bgPrimary text-text-weak`}>
        <NextTopLoader color="#84cc16" height={4} />
        <Header />
        <Toaster/>
        <main className="h-screen max-w-[1200px] mx-auto pt-20">
          {children}
        </main>
      </body>
    </html>
  )
}
